services:
  - type: web
    name: habitfit
    env: static
    buildCommand: ""
    staticPublishPath: "./"
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
